import type { LearningObjective, SkillId, SourceRef, TheoryQuestion } from './types'

/**
 * THEORY QUESTION BANK — v0 (demonstrator, 21 items).
 *
 * Every item is `draft`. Rule citations marked `confidence: 'checked'` were
 * compared by the developer against the text of Trafikkreglene on Lovdata
 * (7 Oct 2026). That is NOT a professional review — approval requires a
 * qualified Norwegian trafikklærer (see /#/faglig).
 */

const TR = 'https://lovdata.no/dokument/SF/forskrift/1986-03-21-747'
const SKILT = 'https://lovdata.no/dokument/SF/forskrift/2005-10-07-1219'
const SVV = 'https://www.vegvesen.no/forerkort/'

const tr = (section: string, confidence: SourceRef['confidence'] = 'checked'): SourceRef => ({
  publisher: 'Lovdata',
  title: 'Forskrift om kjørende og gående trafikk (trafikkregler)',
  section,
  url: TR,
  confidence,
})
const skilt = (section: string): SourceRef => ({ publisher: 'Lovdata', title: 'Skiltforskriften', section, url: SKILT, confidence: 'uncertain' })
const svv = (title: string): SourceRef => ({ publisher: 'Statens vegvesen', title, url: SVV, confidence: 'uncertain' })

export const OBJECTIVES: LearningObjective[] = [
  { id: 'lo-hoyreregel', text: 'Kjenne igjen et uregulert kryss og bruke høyreregelen.', skills: ['trafficRules', 'intersections'] },
  { id: 'lo-vise-vikeplikt', text: 'Vise tydelig og i god tid at du viker.', skills: ['trafficRules', 'speedAdaptation'] },
  { id: 'lo-oversikt', text: 'Tilpasse farten til det du faktisk kan se.', skills: ['speedAdaptation', 'observation'] },
  { id: 'lo-skilt-foran-regler', text: 'Vite at skilt og oppmerking går foran de generelle trafikkreglene.', skills: ['trafficRules'] },
  { id: 'lo-barn', text: 'Forutse barn ved vegen og holde lav fart.', skills: ['hazardAwareness', 'pedestrians', 'speedAdaptation'] },
  { id: 'lo-syklist-sving', text: 'Vike for syklister rett fram når du svinger, og sjekke blindsonen.', skills: ['cyclists', 'observation', 'trafficRules'] },
  { id: 'lo-gangfelt', text: 'Vike for gående i gangfelt og tolke andre kjøretøy som stanser.', skills: ['pedestrians', 'trafficRules', 'hazardAwareness'] },
  { id: 'lo-rundkjoring', text: 'Kjøre inn i, gjennom og ut av en rundkjøring trygt.', skills: ['roundabouts', 'positioning', 'trafficRules'] },
  { id: 'lo-avkjorsel', text: 'Vike for all trafikk når du kommer fra en avkjørsel eller parkeringsplass.', skills: ['trafficRules', 'intersections'] },
]

const draft = { version: 1, professionalReviewStatus: 'draft' as const, reviewHistory: [] }

export const QUESTIONS: TheoryQuestion[] = [
  /* ───────────── S1 · høyreregel ───────────── */
  {
    ...draft,
    id: 'q-s1-hoyreregel',
    category: 'vikeplikt',
    topic: 'Vikeplikt',
    subtopic: 'Høyreregelen',
    difficulty: 1,
    questionType: 'situational',
    prompt: 'Kryss i boligfelt. Ingen skilt, ingen oppmerking. En bil kommer fra høyre samtidig med deg. Hvem kjører først?',
    imageOrSceneReference: { kind: 'diagram', diagram: 'kryss-hoyre' },
    answerOptions: [
      { id: 'a', text: 'Bilen fra høyre' },
      { id: 'b', text: 'Jeg – jeg kjører på den største vegen' },
      { id: 'c', text: 'Den som kommer først fram til krysset' },
      { id: 'd', text: 'Den som har høyest fart' },
    ],
    correctAnswer: 'a',
    explanation: 'Uten skilt, lyssignal eller oppmerking gjelder høyreregelen: du har vikeplikt for kjøretøy som kommer fra høyre.',
    misconception: {
      b: 'Hvor stor vegen ser ut, avgjør ikke vikeplikten. Bare skilt (f.eks. forkjørsvei) kan endre høyreregelen.',
      c: 'Høyreregelen gjelder selv om du er litt tidligere ute. Den du skal vike for, skal ikke hindres eller forstyrres.',
      d: 'Fart gir aldri forkjørsrett. Mer fart gir bare lengre stopplengde.',
    },
    linkedScenarioIds: ['s1-hoyreregel'],
    learningObjectiveIds: ['lo-hoyreregel'],
    skills: { trafficRules: 1, intersections: 0.8 },
    sourceMetadata: [tr('§ 7 nr. 2')],
  },
  {
    ...draft,
    id: 'q-s1-vise-vikeplikt',
    category: 'vikeplikt',
    topic: 'Vikeplikt',
    subtopic: 'Vise at du viker',
    difficulty: 1,
    questionType: 'multiple_choice',
    prompt: 'Du har vikeplikt i et kryss. Hvordan viser du det til den andre sjåføren?',
    answerOptions: [
      { id: 'a', text: 'Jeg setter ned farten eller stanser i god tid' },
      { id: 'b', text: 'Jeg blinker med lysene' },
      { id: 'c', text: 'Jeg vinker den andre fram' },
      { id: 'd', text: 'Jeg ruller sakte helt fram til midten av krysset' },
    ],
    correctAnswer: 'a',
    explanation: 'Den som har vikeplikt skal vise det tydelig ved i god tid å sette ned farten eller stanse. Da slipper den andre å lure på hva du gjør.',
    misconception: {
      b: 'Lyssignaler kan misforstås. Farten er det tydeligste signalet.',
      c: 'Vinking kan misforstås og fjerner ikke din egen vikeplikt.',
      d: 'Ruller du ut i krysset, hindrer og forstyrrer du den du skal vike for.',
    },
    linkedScenarioIds: ['s1-hoyreregel'],
    learningObjectiveIds: ['lo-vise-vikeplikt'],
    skills: { trafficRules: 0.8, speedAdaptation: 0.5 },
    sourceMetadata: [tr('§ 7 nr. 1')],
  },
  {
    ...draft,
    id: 'q-s1-hekk',
    category: 'risiko',
    topic: 'Oversikt',
    subtopic: 'Sikthindring i kryss',
    difficulty: 2,
    questionType: 'hazard_recognition',
    prompt: 'En høy hekk står på hjørnet til høyre for deg før krysset. Hva betyr det for kjøringen din?',
    imageOrSceneReference: { kind: 'scenario', scenarioId: 's1-hoyreregel', stepId: 'priority' },
    answerOptions: [
      { id: 'a', text: 'Den skjuler trafikk fra høyre – jeg må senke farten til jeg har oversikt' },
      { id: 'b', text: 'Den viser at jeg kjører på forkjørsvei' },
      { id: 'c', text: 'Ingenting, så lenge jeg holder fartsgrensen' },
    ],
    correctAnswer: 'a',
    explanation: 'Du må kunne stanse på den strekningen du har oversikt over. Når hekken skjuler sidevegen, må farten ned før krysset.',
    misconception: {
      b: 'Hekker og hus sier ingenting om vikeplikt. Bare skilt og oppmerking gjør det.',
      c: 'Fartsgrensen er en øvre grense. Farten skal tilpasses det du kan se.',
    },
    linkedScenarioIds: ['s1-hoyreregel'],
    learningObjectiveIds: ['lo-oversikt'],
    skills: { observation: 0.8, speedAdaptation: 0.8, riskUnderstanding: 0.6 },
    sourceMetadata: [tr('§ 13 nr. 1')],
  },
  {
    ...draft,
    id: 'q-s1-venstre',
    category: 'vikeplikt',
    topic: 'Vikeplikt',
    subtopic: 'Høyreregelen – motsatt side',
    difficulty: 2,
    questionType: 'what_happens_next',
    prompt: 'Samme kryss, men nå kommer bilen fra VENSTRE. Hva gjør du?',
    imageOrSceneReference: { kind: 'diagram', diagram: 'kryss-venstre' },
    answerOptions: [
      { id: 'a', text: 'Den har vikeplikt for meg, men jeg følger med til jeg ser at den viker' },
      { id: 'b', text: 'Jeg har vikeplikt og må stanse' },
      { id: 'c', text: 'Jeg øker farten for å komme meg over først' },
    ],
    correctAnswer: 'a',
    explanation: 'Nå er det du som kommer fra høyre sett fra den andre bilen, så den skal vike. Men forkjørsrett er ingen garanti – se etter at den faktisk senker farten.',
    misconception: {
      b: 'Høyreregelen gjelder trafikk fra høyre. Her er det den andre som har vikeplikt.',
      c: 'Å øke farten gjør det vanskeligere for begge å rette opp en feil.',
    },
    linkedScenarioIds: ['s1-hoyreregel'],
    learningObjectiveIds: ['lo-hoyreregel'],
    skills: { trafficRules: 0.8, intersections: 0.8, riskUnderstanding: 0.4 },
    sourceMetadata: [tr('§ 7 nr. 2'), tr('§ 7 nr. 1')],
  },
  {
    ...draft,
    id: 'q-s1-forkjorsvei',
    category: 'skilt',
    topic: 'Skilt',
    subtopic: 'Forkjørsvei',
    difficulty: 2,
    questionType: 'sign_recognition',
    prompt: 'Du har passert dette skiltet. Gjelder høyreregelen i neste kryss?',
    imageOrSceneReference: { kind: 'sign', sign: 'forkjorsvei' },
    answerOptions: [
      { id: 'a', text: 'Nei – jeg kjører på forkjørsvei, og trafikk fra sidevegene skal vike' },
      { id: 'b', text: 'Ja – høyreregelen gjelder alltid' },
      { id: 'c', text: 'Bare hvis det er mørkt' },
    ],
    correctAnswer: 'a',
    explanation: 'Skilt og oppmerking går foran de generelle trafikkreglene. På forkjørsvei har kryssende trafikk vikeplikt for deg.',
    misconception: { b: 'Høyreregelen gjelder bare der skilt eller lyssignal ikke bestemmer noe annet.' },
    linkedScenarioIds: ['s1-hoyreregel'],
    learningObjectiveIds: ['lo-skilt-foran-regler'],
    skills: { trafficRules: 1, intersections: 0.5 },
    sourceMetadata: [tr('§ 3 nr. 1'), skilt('Skilt 208 Forkjørsveg')],
  },

  /* ───────────── S2 · ballen ───────────── */
  {
    ...draft,
    id: 'q-s2-ball',
    category: 'myke-trafikanter',
    topic: 'Barn',
    subtopic: 'Forutse barn',
    difficulty: 1,
    questionType: 'hazard_recognition',
    prompt: 'En ball triller ut i vegen mellom to parkerte biler. Hva bør du forvente?',
    imageOrSceneReference: { kind: 'diagram', diagram: 'ball-barn' },
    answerOptions: [
      { id: 'a', text: 'At et barn kan komme løpende etter ballen' },
      { id: 'b', text: 'Ingenting – en ball er ufarlig' },
      { id: 'c', text: 'At ballen spretter tilbake på fortauet' },
    ],
    correctAnswer: 'a',
    explanation: 'Barn følger ballen, ikke trafikken. Senk farten og vær klar til å stanse straks.',
    linkedScenarioIds: ['s2-ballen'],
    learningObjectiveIds: ['lo-barn'],
    skills: { hazardAwareness: 1, pedestrians: 0.7 },
    sourceMetadata: [tr('§ 13 nr. 2')],
  },
  {
    ...draft,
    id: 'q-s2-barn-fart',
    category: 'myke-trafikanter',
    topic: 'Barn',
    subtopic: 'Fart forbi barn',
    difficulty: 2,
    questionType: 'multiple_choice',
    prompt: 'Du skal passere barn som leker ved vegkanten. Hva krever trafikkreglene?',
    answerOptions: [
      { id: 'a', text: 'Tilstrekkelig liten fart, og være klar til å stanse straks' },
      { id: 'b', text: 'Å holde fartsgrensen – da er det nok' },
      { id: 'c', text: 'Å tute så barna flytter seg' },
    ],
    correctAnswer: 'a',
    explanation: 'Ved barn på eller ved vegen skal du i særlig grad holde liten fart og om nødvendig stanse straks.',
    misconception: { b: 'Fartsgrensen er en øvre grense. Ved barn kreves det lavere fart.' },
    linkedScenarioIds: ['s2-ballen'],
    learningObjectiveIds: ['lo-barn'],
    skills: { speedAdaptation: 1, pedestrians: 0.8, trafficRules: 0.5 },
    sourceMetadata: [tr('§ 13 nr. 2')],
  },
  {
    ...draft,
    id: 'q-s2-30-50',
    category: 'fart-og-avstand',
    topic: 'Fart',
    subtopic: 'Stopplengde',
    difficulty: 2,
    questionType: 'multiple_choice',
    prompt: 'Hvorfor er 30 km/t mye tryggere enn 50 km/t i en boliggate?',
    answerOptions: [
      { id: 'a', text: 'Stopplengden blir mye kortere, og en påkjørt fotgjenger har langt større sjanse til å overleve' },
      { id: 'b', text: 'Bilen bruker mindre drivstoff' },
      { id: 'c', text: 'Det er liten forskjell' },
    ],
    correctAnswer: 'a',
    explanation: 'Både reaksjonslengden og bremselengden øker med farten – bremselengden omtrent med kvadratet av farten.',
    linkedScenarioIds: ['s2-ballen'],
    learningObjectiveIds: ['lo-barn', 'lo-oversikt'],
    skills: { speedAdaptation: 0.8, riskUnderstanding: 0.8 },
    sourceMetadata: [svv('Fart og stopplengde (læreplan klasse B)')],
  },

  /* ───────────── S3 · syklisten ───────────── */
  {
    ...draft,
    id: 'q-s3-vikeplikt-sving',
    category: 'myke-trafikanter',
    topic: 'Syklister',
    subtopic: 'Høyresving over sykkelfelt',
    difficulty: 1,
    questionType: 'situational',
    prompt: 'Du skal svinge til høyre. En syklist kommer bakfra i sykkelfeltet og skal rett fram. Hvem har vikeplikt?',
    imageOrSceneReference: { kind: 'diagram', diagram: 'sykkelfelt-hoyresving' },
    answerOptions: [
      { id: 'a', text: 'Jeg – den som svinger, viker for syklende som skal rett fram' },
      { id: 'b', text: 'Syklisten, fordi bilen er større' },
      { id: 'c', text: 'Den som er først i krysset' },
    ],
    correctAnswer: 'a',
    explanation: 'Kjørende som vil svinge har vikeplikt for gående og syklende som skal rett fram.',
    linkedScenarioIds: ['s3-syklisten'],
    learningObjectiveIds: ['lo-syklist-sving'],
    skills: { cyclists: 1, trafficRules: 0.8 },
    sourceMetadata: [tr('§ 7 nr. 3')],
  },
  {
    ...draft,
    id: 'q-s3-rekkefolge',
    category: 'myke-trafikanter',
    topic: 'Syklister',
    subtopic: 'Observasjon før sving',
    difficulty: 2,
    questionType: 'ordering',
    prompt: 'Sett i riktig rekkefølge før du svinger til høyre over et sykkelfelt.',
    answerOptions: [
      { id: 'speil', text: 'Sjekk speilet' },
      { id: 'tegn', text: 'Gi tegn med blinklys' },
      { id: 'blind', text: 'Sjekk blindsonen over skulderen' },
      { id: 'sving', text: 'Sving når sykkelfeltet er fritt' },
    ],
    correctAnswer: ['speil', 'tegn', 'blind', 'sving'],
    explanation: 'Speil – tegn – blindsone – sving. Blindsonen sjekkes rett før svingen, fordi en syklist kan ha kommet inn der etter at du så i speilet.',
    linkedScenarioIds: ['s3-syklisten'],
    learningObjectiveIds: ['lo-syklist-sving'],
    skills: { observation: 1, cyclists: 0.7 },
    sourceMetadata: [svv('Observasjon og svinging (læreplan klasse B)')],
  },
  {
    ...draft,
    id: 'q-s3-blindsone',
    category: 'myke-trafikanter',
    topic: 'Syklister',
    subtopic: 'Blindsone',
    difficulty: 1,
    questionType: 'multiple_choice',
    prompt: 'Hvor er en syklist vanskeligst å se når du skal svinge til høyre?',
    answerOptions: [
      { id: 'a', text: 'Bak og til høyre for bilen – i blindsonen' },
      { id: 'b', text: 'Rett foran bilen' },
      { id: 'c', text: 'Midt i bakspeilet' },
    ],
    correctAnswer: 'a',
    explanation: 'Speilene dekker ikke alt. Området skrått bak til høyre må sjekkes med et raskt blikk over skulderen.',
    linkedScenarioIds: ['s3-syklisten'],
    learningObjectiveIds: ['lo-syklist-sving'],
    skills: { observation: 0.9, cyclists: 0.6 },
    sourceMetadata: [svv('Blindsone (læreplan klasse B)')],
  },

  /* ───────────── S4 · gangfelt ───────────── */
  {
    ...draft,
    id: 'q-s4-gaende-i-gangfelt',
    category: 'myke-trafikanter',
    topic: 'Fotgjengere',
    subtopic: 'Gangfelt',
    difficulty: 1,
    questionType: 'situational',
    prompt: 'En fotgjenger har gått ut i gangfeltet foran deg. Gangfeltet har ikke lyssignal. Hva gjør du?',
    imageOrSceneReference: { kind: 'diagram', diagram: 'gangfelt-fotgjenger' },
    answerOptions: [
      { id: 'a', text: 'Stanser og lar fotgjengeren gå over' },
      { id: 'b', text: 'Kjører rolig forbi bak fotgjengeren' },
      { id: 'c', text: 'Tuter for å varsle' },
    ],
    correctAnswer: 'a',
    explanation: 'Ved gangfelt uten lyssignal eller politi har kjørende vikeplikt for gående som er i gangfeltet.',
    linkedScenarioIds: ['s4-gangfelt'],
    learningObjectiveIds: ['lo-gangfelt'],
    skills: { pedestrians: 1, trafficRules: 0.8 },
    sourceMetadata: [tr('§ 9 nr. 2')],
  },
  {
    ...draft,
    id: 'q-s4-skjult',
    category: 'risiko',
    topic: 'Fotgjengere',
    subtopic: 'Skjult fotgjenger',
    difficulty: 3,
    questionType: 'hazard_recognition',
    prompt: 'Bilen i feltet ved siden av deg stanser foran et gangfelt. Hva bør du tenke?',
    imageOrSceneReference: { kind: 'scenario', scenarioId: 's4-gangfelt' },
    answerOptions: [
      { id: 'a', text: 'Den kan stanse for en fotgjenger jeg ikke ser – jeg senker farten og er klar til å stanse' },
      { id: 'b', text: 'Den har nok motorstopp – jeg kjører forbi' },
      { id: 'c', text: 'Jeg kjører forbi raskt før fotgjengeren kommer' },
    ],
    correctAnswer: 'a',
    explanation: 'Et kjøretøy som stanser foran et gangfelt, kan skjule en fotgjenger. Kjør aldri forbi i den situasjonen uten full oversikt.',
    linkedScenarioIds: ['s4-gangfelt'],
    learningObjectiveIds: ['lo-gangfelt'],
    skills: { hazardAwareness: 1, pedestrians: 0.8, observation: 0.6 },
    sourceMetadata: [tr('§ 9 nr. 2'), tr('Forbikjøring ved gangfelt – paragraf må verifiseres', 'uncertain')],
  },
  {
    ...draft,
    id: 'q-s4-skilt',
    category: 'skilt',
    topic: 'Skilt',
    subtopic: 'Gangfelt',
    difficulty: 1,
    questionType: 'sign_recognition',
    prompt: 'Hva betyr dette skiltet?',
    imageOrSceneReference: { kind: 'sign', sign: 'gangfelt' },
    answerOptions: [
      { id: 'a', text: 'Gangfelt' },
      { id: 'b', text: 'Gågate' },
      { id: 'c', text: 'Fortau slutter' },
    ],
    correctAnswer: 'a',
    explanation: 'Skiltet markerer et gangfelt. Du skal nærme deg med særlig aktsomhet.',
    linkedScenarioIds: ['s4-gangfelt'],
    learningObjectiveIds: ['lo-gangfelt'],
    skills: { trafficRules: 0.6, pedestrians: 0.4 },
    sourceMetadata: [skilt('Skilt 516 Gangfelt')],
  },

  /* ───────────── S5 · rundkjøring ───────────── */
  {
    ...draft,
    id: 'q-s5-blinklys',
    category: 'kryss-og-rundkjoring',
    topic: 'Rundkjøring',
    subtopic: 'Tegngiving',
    difficulty: 1,
    questionType: 'situational',
    prompt: 'Når skal du bruke blinklys i en rundkjøring?',
    imageOrSceneReference: { kind: 'diagram', diagram: 'rundkjoring-utkjoring' },
    answerOptions: [
      { id: 'a', text: 'Høyre blinklys før jeg kjører ut' },
      { id: 'b', text: 'Venstre blinklys hele vegen rundt' },
      { id: 'c', text: 'Aldri – alle vet hvor jeg skal' },
    ],
    correctAnswer: 'a',
    explanation: 'Gi tegn til høyre før du kjører ut. Da vet de som venter på å kjøre inn, at de kan bruke luken.',
    linkedScenarioIds: ['s5-rushtrafikk'],
    learningObjectiveIds: ['lo-rundkjoring'],
    skills: { roundabouts: 1, positioning: 0.4 },
    sourceMetadata: [svv('Kjøring i rundkjøring (læreplan klasse B)')],
  },
  {
    ...draft,
    id: 'q-s5-innkjoring',
    category: 'kryss-og-rundkjoring',
    topic: 'Rundkjøring',
    subtopic: 'Vikeplikt ved innkjøring',
    difficulty: 2,
    questionType: 'multiple_choice',
    prompt: 'Du skal inn i en rundkjøring med vikepliktskilt. Hvem må vike?',
    answerOptions: [
      { id: 'a', text: 'Jeg, for trafikken som allerede er i rundkjøringen' },
      { id: 'b', text: 'De som er i rundkjøringen, for meg' },
      { id: 'c', text: 'Den som kommer fra høyre' },
    ],
    correctAnswer: 'a',
    explanation: 'Skiltet går foran høyreregelen. Vikepliktskilt ved innkjøringen betyr at du viker for trafikken i rundkjøringen.',
    misconception: { c: 'Høyreregelen gjelder ikke når et skilt bestemmer noe annet.' },
    linkedScenarioIds: ['s5-rushtrafikk'],
    learningObjectiveIds: ['lo-rundkjoring', 'lo-skilt-foran-regler'],
    skills: { roundabouts: 0.9, trafficRules: 0.8 },
    sourceMetadata: [tr('§ 3 nr. 1'), skilt('Skilt 202 Vikeplikt')],
  },
  {
    ...draft,
    id: 'q-s5-gangfelt-utkjoring',
    category: 'kryss-og-rundkjoring',
    topic: 'Rundkjøring',
    subtopic: 'Gangfelt i utkjøringen',
    difficulty: 2,
    questionType: 'hazard_recognition',
    prompt: 'En fotgjenger venter ved gangfeltet i utkjøringen du skal ta. Hva er riktig?',
    answerOptions: [
      { id: 'a', text: 'Planlegge å stanse – går fotgjengeren ut, har jeg vikeplikt' },
      { id: 'b', text: 'Akselerere ut av rundkjøringen før fotgjengeren går' },
      { id: 'c', text: 'Stanse inne i rundkjøringen til fotgjengeren er borte' },
    ],
    correctAnswer: 'a',
    explanation: 'Se etter gående allerede før du kjører ut, og hold en fart som lar deg stanse foran gangfeltet.',
    linkedScenarioIds: ['s5-rushtrafikk'],
    learningObjectiveIds: ['lo-rundkjoring', 'lo-gangfelt'],
    skills: { pedestrians: 0.8, roundabouts: 0.6, hazardAwareness: 0.6 },
    sourceMetadata: [tr('§ 9 nr. 2')],
  },

  /* ───────────── general (theory test pool) ───────────── */
  {
    ...draft,
    id: 'q-g-avkjorsel',
    category: 'vikeplikt',
    topic: 'Vikeplikt',
    subtopic: 'Avkjørsel og parkeringsplass',
    difficulty: 1,
    questionType: 'situational',
    prompt: 'Du kjører ut fra en parkeringsplass og inn på vegen. Hvem har vikeplikt?',
    imageOrSceneReference: { kind: 'diagram', diagram: 'avkjorsel' },
    answerOptions: [
      { id: 'a', text: 'Jeg, for all annen trafikk' },
      { id: 'b', text: 'Trafikk fra høyre har vikeplikt for meg' },
      { id: 'c', text: 'Ingen har vikeplikt' },
    ],
    correctAnswer: 'a',
    explanation: 'Kommer du fra parkeringsplass, eiendom, bensinstasjon eller liknende, har du vikeplikt for annen trafikant.',
    misconception: { b: 'Høyreregelen gjelder ikke når du kommer fra en avkjørsel.' },
    linkedScenarioIds: ['s1-hoyreregel'],
    learningObjectiveIds: ['lo-avkjorsel'],
    skills: { trafficRules: 1, intersections: 0.5 },
    sourceMetadata: [tr('§ 7 nr. 4')],
  },
  {
    ...draft,
    id: 'q-g-skilt-foran',
    category: 'vikeplikt',
    topic: 'Vikeplikt',
    subtopic: 'Skilt foran trafikkregler',
    difficulty: 2,
    questionType: 'multiple_choice',
    prompt: 'Det står vikepliktskilt der du kommer inn i et kryss, men en bil kommer fra venstre. Hva gjelder?',
    imageOrSceneReference: { kind: 'sign', sign: 'vikeplikt' },
    answerOptions: [
      { id: 'a', text: 'Skiltet – jeg har vikeplikt for trafikk fra begge sider' },
      { id: 'b', text: 'Høyreregelen – bilen fra venstre må vike' },
      { id: 'c', text: 'Den som kommer først' },
    ],
    correctAnswer: 'a',
    explanation: 'Anvisninger fra skilt, lyssignal og oppmerking gjelder foran trafikkreglene.',
    linkedScenarioIds: ['s1-hoyreregel'],
    learningObjectiveIds: ['lo-skilt-foran-regler'],
    skills: { trafficRules: 1 },
    sourceMetadata: [tr('§ 3 nr. 1'), skilt('Skilt 202 Vikeplikt')],
  },
  {
    ...draft,
    id: 'q-g-oversikt',
    category: 'fart-og-avstand',
    topic: 'Fart',
    subtopic: 'Stanse innenfor oversikt',
    difficulty: 2,
    questionType: 'multiple_choice',
    prompt: 'Du kjører mot en uoversiktlig sving. Hva bestemmer hvor fort du kan kjøre?',
    answerOptions: [
      { id: 'a', text: 'At jeg kan stanse på strekningen jeg har oversikt over' },
      { id: 'b', text: 'Bare fartsgrensen' },
      { id: 'c', text: 'Hvor fort de andre kjører' },
    ],
    correctAnswer: 'a',
    explanation: 'Du må kunne stanse på den strekningen du har oversikt over, og foran enhver hindring du kan regne med.',
    linkedScenarioIds: ['s1-hoyreregel', 's2-ballen'],
    learningObjectiveIds: ['lo-oversikt'],
    skills: { speedAdaptation: 1, riskUnderstanding: 0.6 },
    sourceMetadata: [tr('§ 13 nr. 1')],
  },
  {
    ...draft,
    id: 'q-g-vikeplikt-skilt',
    category: 'skilt',
    topic: 'Skilt',
    subtopic: 'Vikeplikt',
    difficulty: 1,
    questionType: 'sign_recognition',
    prompt: 'Hva betyr dette skiltet?',
    imageOrSceneReference: { kind: 'sign', sign: 'vikeplikt' },
    answerOptions: [
      { id: 'a', text: 'Vikeplikt' },
      { id: 'b', text: 'Farlig sving' },
      { id: 'c', text: 'Innkjøring forbudt' },
    ],
    correctAnswer: 'a',
    explanation: 'Trekanten med spissen ned betyr vikeplikt for trafikk på vegen du kommer inn på.',
    linkedScenarioIds: ['s5-rushtrafikk'],
    learningObjectiveIds: ['lo-skilt-foran-regler'],
    skills: { trafficRules: 0.7 },
    sourceMetadata: [skilt('Skilt 202 Vikeplikt')],
  },
]

export const QUESTION_BY_ID = new Map(QUESTIONS.map((q) => [q.id, q]))

/** Questions that check a scenario's lesson (first = most central). */
export function questionsForScenario(scenarioId: string): TheoryQuestion[] {
  return QUESTIONS.filter((q) => q.linkedScenarioIds[0] === scenarioId)
}

/** The three contextual questions shown after a scenario + one recall/variant item. */
export const SCENARIO_LOOP: Record<string, { questions: string[]; recall: string }> = {
  's1-hoyreregel': { questions: ['q-s1-hoyreregel', 'q-s1-vise-vikeplikt', 'q-s1-hekk'], recall: 'q-s1-venstre' },
  's2-ballen': { questions: ['q-s2-ball', 'q-s2-barn-fart', 'q-s2-30-50'], recall: 'q-g-oversikt' },
  's3-syklisten': { questions: ['q-s3-vikeplikt-sving', 'q-s3-blindsone', 'q-s3-rekkefolge'], recall: 'q-g-avkjorsel' },
  's4-gangfelt': { questions: ['q-s4-gaende-i-gangfelt', 'q-s4-skjult', 'q-s4-skilt'], recall: 'q-s5-gangfelt-utkjoring' },
  's5-rushtrafikk': { questions: ['q-s5-innkjoring', 'q-s5-blinklys', 'q-s5-gangfelt-utkjoring'], recall: 'q-g-skilt-foran' },
}

/** Skills a scenario exercises (applied evidence), weighted. */
export const SCENARIO_SKILLS: Record<string, Partial<Record<SkillId, number>>> = {
  's1-hoyreregel': { trafficRules: 1, intersections: 1, observation: 0.6, riskUnderstanding: 0.5 },
  's2-ballen': { hazardAwareness: 1, pedestrians: 0.8, speedAdaptation: 0.8 },
  's3-syklisten': { cyclists: 1, observation: 1, trafficRules: 0.6 },
  's4-gangfelt': { pedestrians: 1, trafficRules: 0.7, hazardAwareness: 0.8 },
  's5-rushtrafikk': { roundabouts: 1, observation: 0.8, positioning: 0.7, pedestrians: 0.5 },
  practice: { observation: 1, speedAdaptation: 1, positioning: 1, trafficRules: 1, intersections: 0.6 },
}

/** Rule card text for the "LÆR REGELEN" panel (kept beside the bank so a reviewer sees both). */
export const RULE_CARDS: Record<string, { title: string; body: string; diagram: import('./types').DiagramId; source: SourceRef }> = {
  's1-hoyreregel': {
    title: 'Høyreregelen',
    body: 'Uten skilt, lyssignal eller oppmerking har du vikeplikt for kjøretøy fra høyre. Vis det i god tid: senk farten eller stans.',
    diagram: 'kryss-hoyre',
    source: tr('§ 7 nr. 1 og 2'),
  },
  's2-ballen': {
    title: 'Barn ved vegen',
    body: 'Ved barn på eller ved vegen skal du holde særlig lav fart og kunne stanse straks. En ball betyr ofte et barn.',
    diagram: 'ball-barn',
    source: tr('§ 13 nr. 2'),
  },
  's3-syklisten': {
    title: 'Sving over sykkelfelt',
    body: 'Den som svinger, har vikeplikt for syklende som skal rett fram. Speil – tegn – blindsone – sving.',
    diagram: 'sykkelfelt-hoyresving',
    source: tr('§ 7 nr. 3'),
  },
  's4-gangfelt': {
    title: 'Gangfelt',
    body: 'Ved gangfelt uten lyssignal har du vikeplikt for gående i gangfeltet. Stanser en bil foran gangfeltet, kan den skjule noen.',
    diagram: 'gangfelt-fotgjenger',
    source: tr('§ 9 nr. 2'),
  },
  's5-rushtrafikk': {
    title: 'Rundkjøring',
    body: 'Vik for trafikken i rundkjøringen når det står vikepliktskilt. Gi tegn til høyre før du kjører ut, og se etter gående.',
    diagram: 'rundkjoring-utkjoring',
    source: svv('Kjøring i rundkjøring (læreplan klasse B)'),
  },
}
